# Generated by Django 5.0.6 on 2024-05-23 08:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogmodel_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
