# Generated by Django 5.0.6 on 2024-05-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogmodel_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='long_description',
            new_name='test_editor',
        ),
    ]
