# Generated by Django 5.0.6 on 2024-05-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmanufacture',
            options={'verbose_name': 'Product Manufacture', 'verbose_name_plural': 'Product Manufactures'},
        ),
        migrations.AlterField(
            model_name='productcolormodel',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
